### ISSUE TITLE
项目报错 lateinit property zoomImageView has not been initialized

### ISSUE THREAD

**Issue by li-zheng-hao** [lqy20160609/ImageClip#1]
下载项目后直接运行就出现如下错误，没有更改过任何代码

```java
kotlin.UninitializedPropertyAccessException: lateinit property zoomImageView has not been initialized
        at com.liqingyue.imageclip.view.ClipImageView.onDraw(ClipImageView.kt:289)
        at android.view.View.draw(View.java:20234)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1963)
        at android.view.View.draw(View.java:20237)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.updateDisplayListIfDirty(View.java:19100)
        at android.view.View.draw(View.java:19962)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20237)
        at com.android.internal.policy.DecorView.draw(DecorView.java:784)
        at android.view.View.updateDisplayListIfDirty(View.java:19109)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:695)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:701)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:810)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3405)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3189)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2558)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1529)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7412)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
        at android.view.Choreographer.doCallbacks(Choreographer.java:839)
        at android.view.Choreographer.doFrame(Choreographer.java:774)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by OumaSyuu** [comment]
由于这个项目中view的onDraw可能会比设置图片的接口要快，所以需要对这些对象进行是否初始化的判断，可以在出问题的地方加上：
```kotlin
        if (!this::clipImageWindowView.isInitialized)
            return
        if (!this::zoomImageView.isInitialized)
            return
```
